add a procedure to recover mon from OSDs
cybozu-go/rook pull request #4
Opened 2021-02-03 01:37 UTC by llamerada-jp

Signed-off-by: Yuji Ito <llamerada.jp@gmail.com>

**Description of your changes:**

**Which issue is resolved by this Pull Request:**
Resolves #

**Checklist:**

- [ ] **Commit Message Formatting**: Commit titles and messages follow guidelines in the [developer guide](https://rook.io/docs/rook/master/development-flow.html#commit-structure).
- [ ] **Skip Tests for Docs**: Add the flag for skipping the build if this is only a documentation change. See [here](https://github.com/rook/rook/blob/master/INSTALL.md#skip-ci) for the flag.
- [ ] **Skip Unrelated Tests**: Add a flag to run tests for a specific storage provider. See [test options](https://github.com/rook/rook/blob/master/INSTALL.md#test-storage-provider).
- [ ] Reviewed the developer guide on [Submitting a Pull Request](https://rook.io/docs/rook/master/development-flow.html#submitting-a-pull-request)
- [ ] Documentation has been updated, if necessary.
- [ ] Unit tests have been added, if necessary.
- [ ] Integration tests have been added, if necessary.
- [ ] Pending release notes updated with breaking and/or notable changes, if necessary.
- [ ] Upgrade from previous release is tested and upgrade user guide is updated, if necessary.
- [ ] Code generation (`make codegen`) has been run to update object specifications, if necessary.

2021-02-03 08:05 UTC, satoru-takeuchi requested changes

2021-02-03 08:05 UTC, satoru-takeuchi commented on Documentation/ceph-disaster-recovery.md
> +# Check if cluster is recovered
Check if cluster becomes healthy.

2021-02-03 08:05 UTC, satoru-takeuchi commented on Documentation/ceph-disaster-recovery.md
> +It is recommended that you take a copy from the recovered cluster and move the data to the newly recreated cluster.
この節はあえて書かなくてもいいと思います。

2021-02-03 08:49 UTC, toshipp commented on Documentation/ceph-disaster-recovery.md
> +See: https://docs.ceph.com/en/latest/rados/troubleshooting/troubleshooting-mon/#recovery-using-osds
この辺にリンク先の known issue があるので気を付けてねというのも書いておきたいですね。
こんな感じかな。

It is also that known issues described in the ceph document exist, please read it before and carry out the work carefully.

2021-02-03 10:45 UTC, llamerada-jp commented on Documentation/ceph-disaster-recovery.md
> +Stop the operator, mons and OSDs:
自分も MON じゃないかなと考えましたが、同ページの他の場所で mon が使われていたのでそちらにあわせてました。

2021-02-03 11:01 UTC, llamerada-jp commented on Documentation/ceph-disaster-recovery.md
> +It is recommended that you take a copy from the recovered cluster and move the data to the newly recreated cluster.
MGRの設定が復元されない点は残したほうが良いかと思い、240行目に移動しました。
https://github.com/cybozu-go/rook/pull/4/files#diff-0ca833866b2d53e3e162d867120a0b54da02afef2b3b10b276cbda17bf95302eR240

2021-02-04 00:23 UTC, toshipp approved these changes
LGTM

2021-02-04 05:16 UTC, closed without merging